### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by devesh95** [rainforestapp/react-pusher#11]
Given the relatively simple outlined structure here it seems adding in support for React Native should be supported. Currently trying to instantiate a Pusher component inside a React Native tree throws the following exception:

Invariant Violation: Expected a component class, got [Object object].

I presume this is because of the "noscript" tag returned through render(). Is there any way to detect an RN environment and return an empty View instead (if that is indeed the error)?

**Comment by euanlau** [comment]
`nosript` also does not work inside table. Is it possible to render `null` instead?

**Comment by prayogoa** [comment]
This should be doable now, this was written before returning `null` was supported
