### ISSUE TITLE
Following the instructions causes this error

### ISSUE THREAD

**Issue by gotoAndBliss** [rainforestapp/react-pusher#6]
```Uncaught Error: you must set a pusherClient by calling setPusherClient```

My code is simply this 

```javascript
import { setPusherClient } from 'react-pusher';
import Pusher from 'react-pusher';

const pusherClient = new Pusher('xxxx1234567890xxxx', {encrypted: (document.location.protocol == 'https:')});
setPusherClient(pusherClient);
```

It's complaining about not having `setPusherClient` as soon as I define the variable.

**Comment by craigsssmith** [comment]
Try replacing the line:

```js
import Pusher from 'react-pusher';
```

with

```js
import Pusher from 'pusher-js';
```

**Comment by charlie-ablett** [comment]
I'm having the same issue as gotoAndBliss. Applying your suggestion above gives an error: 

`Module not found: Error: Cannot resolve module 'pusher-js' in <app directory>`

If `pusher-js` needs to be installed as well, should it not listed as a dependency or be in the readme?

**Comment by prayogoa** [comment]
`pusher-js` is meant to be a peer dependency, we should update package.json

> The readme on npmjs.com says to
import pusherClient from 'pusher-js';
which seems incorrect?

That should be fine, why do you think it's incorrect?
